### ISSUE TITLE
Traceback on latest 119 startup

### ISSUE THREAD

**Issue by srevenant** [pulsar-edit/pulsar#1060]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

/Applications/Pulsar.app/Contents/Resources/app.asar/src/text-editor-component.js:1776

TypeError: Cannot read property 'element' of undefined
    at TextEditorComponent.didScrollDummyScrollbar (/Applications/Pulsar.app/Contents/Resources/app.asar/src/text-editor-component.js:1776:37)

### Pulsar version

119

### Which OS does this happen on?

🍎 macOS

### OS details

Sonoma

### Which CPU architecture are you running this on?

x86_64/AMD64

### What steps are needed to reproduce this?

I started up after upgrading and got the TB

### Additional Information:

/Applications/Pulsar.app/Contents/Resources/app.asar/src/text-editor-component.js:1776
TypeError: Cannot read property 'element' of undefined
    at TextEditorComponent.didScrollDummyScrollbar (/Applications/Pulsar.app/Contents/Resources/app.asar/src/text-editor-component.js:1776:37)

**Comment by savetheclocktower** [comment]
I've noticed this happening sometimes but haven't been able to pinpoint why. It doesn't seem to affect much, but let us know if it happens routinely.
