### ISSUE TITLE
decreaseNextLineIndentRegex.testSync is not a function

### ISSUE THREAD

**Issue by marziodev** [pulsar-edit/pulsar#1082]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

TypeError: decreaseNextLineIndentRegex.testSync is not a function
    at TextEditor.editor.autoDecreaseIndentForBufferRow (/home/marzio/.var/app/dev.pulsar_edit.Pulsar/data/packages/react/lib/atom-react.coffee:62:56)
    at Selection.insertText (/app/Pulsar/resources/app.asar/src/selection.js:579:19)
    at /app/Pulsar/resources/app.asar/src/text-editor.js:1748:31
    at /app/Pulsar/resources/app.asar/src/text-editor.js:1801:33
    at Array.map (<anonymous>)
    at /app/Pulsar/resources/app.asar/src/text-editor.js:1800:60
    at TextBuffer.transact (/app/Pulsar/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1320:16)
    at TextEditor.transact (/app/Pulsar/resources/app.asar/src/text-editor.js:2467:24)
    at /app/Pulsar/resources/app.asar/src/text-editor.js:1799:19
    at TextEditor.mergeSelections (/app/Pulsar/resources/app.asar/src/text-editor.js:4050:47)
    at TextEditor.mergeIntersectingSelections (/app/Pulsar/resources/app.asar/src/text-editor.js:4015:10)
    at TextEditor.mutateSelectedText (/app/Pulsar/resources/app.asar/src/text-editor.js:1798:17)
    at TextEditor.insertText (/app/Pulsar/resources/app.asar/src/text-editor.js:1747:25)
    at TextEditor.object.<computed> [as insertText] (/app/Pulsar/resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
    at TextEditorComponent.didTextInput (/app/Pulsar/resources/app.asar/src/text-editor-component.js:1845:24)

### Pulsar version

1.120.0

### Which OS does this happen on?

🐧 OpenSUSE based

### OS details

OpenSuse Tumbleweed

### Which CPU architecture are you running this on?

None

### What steps are needed to reproduce this?

In a React project type: "
function Whatever(){} "
When hitting return with the cursor in between the curly brackets, the error appears.

### Additional Information:

![pulsar_bug](https://github.com/user-attachments/assets/40cff746-9a64-41c4-ab79-2848307cc8da)

**Comment by savetheclocktower** [comment]
The [react](https://web.pulsar-edit.dev/packages/react) package is marked as broken because it uses private APIs that are no longer valid.

The good news is that it's no longer needed! The default JavaScript grammar supports JSX and can indent it properly. If you want autocompletion and other features you can use [pulsar-ide-typescript-alpha](https://web.pulsar-edit.dev/packages/pulsar-ide-typescript-alpha).

I'm closing this ticket, but if you have other questions about replacing the functionality of this broken package, reply and I'll see if I can help.

**Comment by marziodev** [comment]
Yes! Now it's working, thank you!
