### ISSUE TITLE
Package Markdown-Preview-Enhanced does not work properly

### ISSUE THREAD

**Issue by kr-cr** [pulsar-edit/pulsar#235]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Does your issue already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

Hello,

I installed and launched the package [Markdown Preview enhanced](https://github.com/shd101wyy/markdown-preview-enhanced/) that still works with the last version of Atom (1.63.1). 

It loads properly, and the markdown preview works, but the right-click menu does not. "Open in Browser" loads nothing, same for "save as Markdown".

The developper Tools show a lot of errors but its hard for me to know which ones are linked to these issues since the same situation in Atom also generate some errors.

I have also opened an issue in [Mardown Preview Enhanced Repository](https://github.com/shd101wyy/markdown-preview-enhanced/issues/1773) because I am note sure which side have to resolve this.

Thank you.

### Which OS does this happen on?

🍎 macOS

### OS details

Mac OS Monterey 12.6

### Which CPU architecture are you running this on?

Apple M1/M2

### What steps are needed to reproduce this?

1. Install Markdown Preview Enhanced with the package manager
2. Launch it with Window → Packages → Markdown Preview Enhanced → Toggle Preview
3. Right Click on the Markdown Preview side
4. Click on "Open in Browser"
5. Nothing happens

### Additional Information:

Version of Pulsar: 1.63.2022121205

**Comment by confused-Techie** [comment]
Thanks for reporting this bug, I just want to confirm, does this specific feature work on Atom?

**Comment by kr-cr** [comment]
Thanks for you reply, yes I confirm it still works on Atom.

**Comment by confused-Techie** [comment]
> Thanks for you reply, yes I confirm it still works on Atom.

Copy that, wanted to ensure this was a proper regression rather than a missing issue on their end.

**Comment by andriandreo** [comment]
In fact if you copy the package folder from the atom installation into the pulsar one, it does work indeed

**Comment by confused-Techie** [comment]
Thanks for keeping up on this issue.

Unfortunate we haven't seen any update from the package side, as in general that's where we would expect to see an issue like this resolved from.

Now I'm not sure if this was the exact error you had originally seen, but unfortunately for me I'm unable to even activate the package:

```
At Cannot find module 'node:fs/promises'
Require stack:
- C:\Users\USER\.pulsar\packages\markdown-preview-enhanced\node_modules\@shd101wyy\mume\out\cjs\index.cjs
- C:\Users\USER\.pulsar\packages\markdown-preview-enhanced\out\src\extension.js
- C:\Users\USER\AppData\Local\Programs\Pulsar\resources\app.asar\src\module-utils.js
- C:\Users\USER\AppData\Local\Programs\Pulsar\resources\app.asar\src\package.js
- C:\Users\USER\AppData\Local\Programs\Pulsar\resources\app.asar\src\package-manager.js
- C:\Users\USER\AppData\Local\Programs\Pulsar\resources\app.asar\src\atom-environment.js
- C:\Users\USER\AppData\Local\Programs\Pulsar\resources\app.asar\src\initialize-application-window.js
- C:\Users\USER\AppData\Local\Programs\Pulsar\resources\app.asar\static\index.html

Error: Cannot find module 'node:fs/promises'
Require stack:
- C:\Users\USER\.pulsar\packages\markdown-preview-enhanced\node_modules\@shd101wyy\mume\out\cjs\index.cjs
- C:\Users\USER\.pulsar\packages\markdown-preview-enhanced\out\src\extension.js
- C:\Users\USER\AppData\Local\Programs\Pulsar\resources\app.asar\src\module-utils.js
- C:\Users\USER\AppData\Local\Programs\Pulsar\resources\app.asar\src\package.js
- C:\Users\USER\AppData\Local\Programs\Pulsar\resources\app.asar\src\package-manager.js
- C:\Users\USER\AppData\Local\Programs\Pulsar\resources\app.asar\src\atom-environment.js
- C:\Users\USER\AppData\Local\Programs\Pulsar\resources\app.asar\src\initialize-application-window.js
- C:\Users\USER\AppData\Local\Programs\Pulsar\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at o._resolveFilename (electron/js2c/renderer_init.js:33:1118)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:317:28)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.o._load (electron/js2c/renderer_init.js:33:379)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (/app.asar/src/native-compile-cache.js:67:27)
    at /packages/markdown-preview-enhanced/node_modules/@shd101wyy/mume/out/cjs/index.cjs:159:7134)
    at /packages/markdown-preview-enhanced/node_modules/@shd101wyy/mume/out/cjs/index.cjs:610:3)
    at Module._compile (/app.asar/src/native-compile-cache.js:120:30)
    at /app.asar/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.o._load (electron/js2c/renderer_init.js:33:379)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (/app.asar/src/native-compile-cache.js:67:27)
    at /packages/markdown-preview-enhanced/out/src/extension.js:13:14)
    at /packages/markdown-preview-enhanced/out/src/extension.js:568:3)
    at Module._compile (/app.asar/src/native-compile-cache.js:120:30)
    at /app.asar/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.o._load (electron/js2c/renderer_init.js:33:379)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (/app.asar/src/native-compile-cache.js:67:27)
    at requireModule (/app.asar/src/module-utils.js:3:17)
    at Package.requireMainModule (/app.asar/src/package.js:912:27)
    at Package.activateNow (/app.asar/src/package.js:232:34)
    at /app.asar/src/package.js:1067:18
    at Function.simpleDispatch (/app.asar/node_modules/event-kit/dist/emitter.js:64:14)
    at Emitter.emit (/app.asar/node_modules/event-kit/dist/emitter.js:257:28)
    at /app.asar/src/package-manager.js:791:36
    at Set.forEach (<anonymous>:null:null)
    at PackageManager.activatePackage (/app.asar/src/package-manager.js:790:37)
    at exit (/app.asar/node_modules/settings-view/lib/package-manager.js:426:25)
    at exit (/app.asar/node_modules/settings-view/lib/package-manager.js:85:26)
    at triggerExitCallback (/app.asar/src/buffered-process.js:280:9)
    at /app.asar/src/buffered-process.js:310:9)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
```

And even further seems this is broken in a downstream dependency of the package itself, which seems to suggest this can only be resolve from the package itself. Now as for the error I'm seeing preventing even activation of the package, it likely will be resolved in the future once we can bump NodeJS further, but I wouldn't wait on that to happen to fix this issue, as that's likely still quite a ways out

**Comment by andriandreo** [comment]
Yes, you're totally right. I was facing the same warnings and errors upon its installation in Pulsar, that's why I tried to copy-paste from Atom. It does work regarding preview, but all the extra output and save-as functionalities are broken...

**Comment by confused-Techie** [comment]
@andriandreo What version of the community package do you have along with your old Atom install? Seems I'd have to grab that exact version to be able to test your previous issue.

But especially now that the package doesn't even activate, doesn't matter if we fix what the previous issue is, seems the author needs to be made aware that their package is broken on Pulsar. Since if it cannot activate, there's nothing Pulsar can really do to make it work

**Comment by kr-cr** [comment]
Thank you for looking at it. 
It appears that on the same time the author of the package has learnt the existence of this project and said he might update it after refactoring the code, see: https://github.com/shd101wyy/vscode-markdown-preview-enhanced/issues/768#issuecomment-1711529812

**Comment by confused-Techie** [comment]
@kr-cr Thats fantastic news! Things being updated there is the best way forward, so that's super exciting to see!

**Comment by andriandreo** [comment]
> @andriandreo What version of the community package do you have along with your old Atom install? Seems I'd have to grab that exact version to be able to test your previous issue.
> 
> But especially now that the package doesn't even activate, doesn't matter if we fix what the previous issue is, seems the author needs to be made aware that their package is broken on Pulsar. Since if it cannot activate, there's nothing Pulsar can really do to make it work

It was `v0.19.2`, but as far as I've tested only the preview works, right-click menu does pretty much nothing.

**Comment by savetheclocktower** [comment]
Based on [this output](https://github.com/pulsar-edit/pulsar/issues/235#issuecomment-1710294878), I wonder if `markdown-preview-enhanced` would work now that we've upgraded to Electron 30.

That error message likely appeared because the version of Node we were stuck on for ages (14.17.0, I believe) was not new enough to support `node:` as a prefix to an import specifier. I don't see any obvious reason why the same code would not work now that we're on Node 20.11.1.

Relatedly: it's telling that the package worked just fine as long as you copied over a folder from an existing Atom installation. This sounds like what happens when a `package.json` doesn't pin to specific version numbers… and a breaking change sneaks into a dependency without that dependency bumping its major version. In this case, the dependency would be `@shd101wyy/mume` — the package that tried to require `node:fs/promises`.

It might eventually be worth exploring a way to use any `package-lock.json` that is found in the package's repo, even if it's an opt-in thing. This is a case where it would be useful to have a snapshot of an exact set of dependencies that produced a known-working package.
