### ISSUE TITLE
Dependence on `ComSpec` causes issues:  `/usr/bin/bash: /s: No such file or directory`

### ISSUE THREAD

**Issue by goyalyashpal** [pulsar-edit/pulsar#482]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

```
.* failed. Hide output…
    /usr/bin/bash: /s: No such file or directory
```

### Pulsar version

1.103.0

### Which OS does this happen on?

🪟 Windows

### OS details

Win 10 22H2

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

Open Settings (bottom right gear icon) > go to any (one or more) of the following:

* Packages > Install (arrive via URI: `atom://` protocol, [example here]): `Installing “uber-juno@0.3.0” failed. Hide output…`
* ~~Themes > Installed themes: ``~~
* Updates > Click "Check for updates": `Fetching outdated packages and themes failed. Hide output…`
* Install Packages > Click "Themes" or "Packages": `Fetching featured packages failed. Hide output…`

[example here]: https://web.pulsar-edit.dev/packages/uber-juno "uber-juno"

### Additional Information:

> _how did you install Pulsar? Was it from our Website?_
> \- @ confused-Techie at https://github.com/pulsar-edit/pulsar/issues/411#issuecomment-1502340975

* I downloaded Pulsar from [github/pulsar/releases]
* I installed Pulsar as admin, in a custom location
* I am using msys2 on my system.
* My system variable for current account (non-admin) is `ComSpec: ...\bash.exe`

[github/pulsar/releases]: https://github.com/pulsar-edit/pulsar/releases/download/v1.103.0/Windows.Pulsar.Setup.1.103.0.exe

**Comment by confused-Techie** [comment]
Thanks a ton for opening an issue for this one.

It sounds almost like Pulsar is having trouble finding your pulsar configuration location, do you have a `%userprofile%/.pulsar/` file on your system?

But otherwise I'll test with installing it to a custom location and see if I can reproduce this

**Comment by goyalyashpal** [comment]
> do you have a `%userprofile%/.pulsar/` file on your system?

yep, the whole folder exists pretty well.

```console
$ ls "$USERPROFILE/.pulsar"
blob-store     config.cson  init.js      packages       storage
compile-cache  github.cson  keymap.cson  snippets.cson  styles.less
```

**Comment by confused-Techie** [comment]
@goyalyashpal So I noticed you used the Linux way to specify the directory location, I wonder if this is something to do with, I'm assuming you are using WSL? 

I have it setup to without any issues, but might depend a bit on how Pulsar is being launched.

Otherwise, tbh I'd thinking this may be related to setting `ComSpec` to being `bash.exe` Pulsar uses a few scripts to launch Pulsar itself and PPM that is intended to integrate with having `ComSpec` set to `cmd.exe` (Or otherwise the default on Windows Systems) and can't say it's ever been tested otherwise.

Is `cmd.exe` still available on your PATH at all? Or would it be possible to test if this behavior still occurs when setting `ComSpec` back to defaults, to see at least if that's the source of the issue

**Comment by goyalyashpal** [comment]
> I wonder if this is something to do with, I'm assuming you are using WSL?

nope, i am not using WSL. It's msys2 - it provides bash etc - which i find much much more pleasant to work with. It's totally standalone, it works with **local system**, doesn't require entering in any special environment like WSL or any other such thing.



> would it be possible to test if this behavior still occurs when setting `ComSpec` back to defaults, to see at least if that's the source of the issue

ohkay, i will see

**Comment by goyalyashpal** [comment]
yep, setting `ComSpec` back to `C:\WINDOWS\system32\cmd.exe` fixed the issues

**Comment by confused-Techie** [comment]
So I'll take a look into this, but do want to mention that it may not be something we can totally resolve.

Since it looks like this issue occurs when `settings-view` `./lib/package-manager.coffee` uses `BufferedProcess` to launch a shell. We don't explicitly invoke any kind of shell, which means either this error is happening within `BufferedProcess` itself, or the handling of PPM.

Now hopefully there is a way to rework this in a way that works for existing users and users like yourself.

But I do want to ask @pulsar-edit/core is this something we want to work to support?

Keep in mind that the first Google Result for setting `Comspec` to `bash` is a [StackOverflow post](https://stackoverflow.com/questions/42761961/change-comspec-from-cmd-exe-to-bash-exe) pointing out the ways this is very likely to break existing applications. 

Although the simplest solution might be to see if either we can launch PPM via a specified CLI, or if we can otherwise optionally change the `./src/package-manager.js` `possibleApmPaths()` to return the `apm.sh` when it detects that `bash.exe` is set as `ComSpec`. (Assuming of course that `bash.exe` is able to let `ppm.sh` run without issue on Windows.

**Comment by confused-Techie** [comment]
So a follow-up here, in `./src/buffered-process.js` uses `child_process` to spawn any shells used, such as those for where these errors are occurring.

In `child_process` itself, when on Windows it will use whatever [`%COMSPEC%` is as the shell](https://nodejs.org/api/child_process.html#default-windows-shell) used to invoke any commands.
Since PPM is not currently compatible with this, one thing we could do is simply check if `%COMSPEC%` is in fact `cmd.exe` and if not, manually use that instead by setting `shell` in the spawn options.

This would effectively ignore any other terminals being used, but might be a good idea, to keep things working.

**Comment by goyalyashpal** [comment]
one more thing, on trying to install that uber-juno with ComSpec:cmd, it threw following error:


-----


### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description



### Steps to Reproduce

1. 
2. 
3. 

**Expected behavior:**



**Actual behavior:**



### Versions

**Atom**: 1.103.0 x64
**Electron**: 12.2.3
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: [uber-juno](https://github.com/JunoLab/uber-juno) package 0.3.0


### Stack Trace

Failed to load the uber-juno package

<details>

```
At D:\ProgramFiles\Pulsar\file:\%USERPROFILE%\.pulsar\packages\uber-juno\lib\incompatible-packages.js: Unexpected reserved word 'package'. (5:11)

  3 | export function checkIncompatible () {
  4 |   let incompat = []
> 5 |   for (let package of atom.packages.getLoadedPackages()) {
    |            ^
  6 |     if (!package.isCompatible()) {
  7 |       incompat.push(package)
  8 |     }

SyntaxError: D:\ProgramFiles\Pulsar\file:\%USERPROFILE%\.pulsar\packages\uber-juno\lib\incompatible-packages.js: Unexpected reserved word 'package'. (5:11)

  3 | export function checkIncompatible () {
  4 |   let incompat = []
> 5 |   for (let package of atom.packages.getLoadedPackages()) {
    |            ^
  6 |     if (!package.isCompatible()) {
  7 |       incompat.push(package)
  8 |     }
    at instantiate (/app.asar/node_modules/@babel/parser/lib/index.js:67:32)
    at constructor (/app.asar/node_modules/@babel/parser/lib/index.js:364:12)
    at FlowParserMixin.raise (/app.asar/node_modules/@babel/parser/lib/index.js:3364:19)
    at FlowParserMixin.checkReservedWord (/app.asar/node_modules/@babel/parser/lib/index.js:12464:12)
    at FlowParserMixin.parseIdentifierName (/app.asar/node_modules/@babel/parser/lib/index.js:12412:12)
    at FlowParserMixin.parseIdentifier (/app.asar/node_modules/@babel/parser/lib/index.js:12387:23)
    at FlowParserMixin.parseBindingAtom (/app.asar/node_modules/@babel/parser/lib/index.js:10563:17)
    at FlowParserMixin.parseBindingAtom (/app.asar/node_modules/@babel/parser/lib/index.js:5927:22)
    at FlowParserMixin.parseVarId (/app.asar/node_modules/@babel/parser/lib/index.js:13598:21)
    at FlowParserMixin.parseVarId (/app.asar/node_modules/@babel/parser/lib/index.js:5940:11)
    at FlowParserMixin.parseVar (/app.asar/node_modules/@babel/parser/lib/index.js:13577:12)
    at FlowParserMixin.parseForStatement (/app.asar/node_modules/@babel/parser/lib/index.js:13221:12)
    at FlowParserMixin.parseStatementContent (/app.asar/node_modules/@babel/parser/lib/index.js:12933:21)
    at FlowParserMixin.parseStatement (/app.asar/node_modules/@babel/parser/lib/index.js:12917:17)
    at FlowParserMixin.parseStatement (/app.asar/node_modules/@babel/parser/lib/index.js:5309:24)
    at FlowParserMixin.parseBlockOrModuleBlockBody (/app.asar/node_modules/@babel/parser/lib/index.js:13497:25)
    at FlowParserMixin.parseBlockBody (/app.asar/node_modules/@babel/parser/lib/index.js:13489:10)
    at FlowParserMixin.parseBlock (/app.asar/node_modules/@babel/parser/lib/index.js:13477:10)
    at FlowParserMixin.parseFunctionBody (/app.asar/node_modules/@babel/parser/lib/index.js:12287:24)
    at FlowParserMixin.parseFunctionBody (/app.asar/node_modules/@babel/parser/lib/index.js:5284:18)
    at FlowParserMixin.parseFunctionBodyAndFinish (/app.asar/node_modules/@babel/parser/lib/index.js:12271:10)
    at FlowParserMixin.parseFunctionBodyAndFinish (/app.asar/node_modules/@babel/parser/lib/index.js:5293:18)
    at /app.asar/node_modules/@babel/parser/lib/index.js:13637:12
    at FlowParserMixin.withSmartMixTopicForbiddingContext (/app.asar/node_modules/@babel/parser/lib/index.js:12617:14)
    at FlowParserMixin.parseFunction (/app.asar/node_modules/@babel/parser/lib/index.js:13636:10)
    at FlowParserMixin.parseFunctionStatement (/app.asar/node_modules/@babel/parser/lib/index.js:13276:17)
    at FlowParserMixin.parseStatementContent (/app.asar/node_modules/@babel/parser/lib/index.js:12947:21)
    at FlowParserMixin.parseStatement (/app.asar/node_modules/@babel/parser/lib/index.js:12917:17)
    at FlowParserMixin.parseStatement (/app.asar/node_modules/@babel/parser/lib/index.js:5309:24)
    at FlowParserMixin.parseExportDeclaration (/app.asar/node_modules/@babel/parser/lib/index.js:14181:17)
    at FlowParserMixin.parseExportDeclaration (/app.asar/node_modules/@babel/parser/lib/index.js:5527:20)
    at FlowParserMixin.maybeParseExportDeclaration (/app.asar/node_modules/@babel/parser/lib/index.js:14135:31)
    at FlowParserMixin.parseExport (/app.asar/node_modules/@babel/parser/lib/index.js:14058:29)
    at FlowParserMixin.parseExport (/app.asar/node_modules/@babel/parser/lib/index.js:5493:24)
    at FlowParserMixin.parseStatementContent (/app.asar/node_modules/@babel/parser/lib/index.js:13020:27)
    at FlowParserMixin.parseStatement (/app.asar/node_modules/@babel/parser/lib/index.js:12917:17)
    at FlowParserMixin.parseStatement (/app.asar/node_modules/@babel/parser/lib/index.js:5309:24)
    at FlowParserMixin.parseBlockOrModuleBlockBody (/app.asar/node_modules/@babel/parser/lib/index.js:13497:25)
    at FlowParserMixin.parseBlockBody (/app.asar/node_modules/@babel/parser/lib/index.js:13489:10)
    at FlowParserMixin.parseProgram (/app.asar/node_modules/@babel/parser/lib/index.js:12832:10)
    at FlowParserMixin.parseTopLevel (/app.asar/node_modules/@babel/parser/lib/index.js:12822:25)
    at FlowParserMixin.parseTopLevel (/app.asar/node_modules/@babel/parser/lib/index.js:6174:28)
    at FlowParserMixin.parse (/app.asar/node_modules/@babel/parser/lib/index.js:14674:10)
    at parse (/app.asar/node_modules/@babel/parser/lib/index.js:14716:38)
    at parser (/app.asar/node_modules/@babel/core/lib/parser/index.js:52:34)
    at parser.next (<anonymous>)
    at normalizeFile (/app.asar/node_modules/@babel/core/lib/transformation/normalize-file.js:87:38)
    at normalizeFile.next (<anonymous>)
    at run (/app.asar/node_modules/@babel/core/lib/transformation/index.js:31:50)
    at run.next (<anonymous>)
    at Object.transform (/app.asar/node_modules/@babel/core/lib/transform.js:25:41)
    at transform.next (<anonymous>)
    at evaluateSync (/app.asar/node_modules/gensync/index.js:251:28)
    at Object.sync (/app.asar/node_modules/gensync/index.js:89:14)
    at Object.exports.compile (/app.asar/src/babel.js:60:16)
    at Object.compile (/app.asar/src/package-transpilation-registry.js:66:27)
    at compileFileAtPath (/app.asar/src/compile-cache.js:106:31)
    at /app.asar/src/compile-cache.js:251:22)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.o._load (electron/js2c/renderer_init.js:33:379)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (/app.asar/src/native-compile-cache.js:67:27)
    at /packages/uber-juno/lib/uber-juno.coffee:3:10)
    at /packages/uber-juno/lib/uber-juno.coffee:1:1)
    at /packages/uber-juno/lib/uber-juno.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:120:30)
    at /app.asar/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.o._load (electron/js2c/renderer_init.js:33:379)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (/app.asar/src/native-compile-cache.js:67:27)
    at requireModule (/app.asar/src/module-utils.js:3:17)
    at Package.requireMainModule (/app.asar/src/package.js:909:27)
    at /app.asar/src/package.js:141:16
    at Package.measure (/app.asar/src/package.js:82:19)
    at Package.load (/app.asar/src/package.js:127:10)
    at PackageManager.loadAvailablePackage (/app.asar/src/package-manager.js:701:10)
    at PackageManager.loadPackage (/app.asar/src/package-manager.js:630:19)
    at PackageManager.activatePackage (/app.asar/src/package-manager.js:774:17)
    at /app.asar/node_modules/settings-view/lib/package-manager.coffee:321:25
    at exit (/app.asar/node_modules/settings-view/lib/package-manager.coffee:68:7)
    at triggerExitCallback (/app.asar/src/buffered-process.js:280:9)
    at /app.asar/src/buffered-process.js:310:9)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
```

</details>

### Commands

```
```

### Non-Core Packages

```
uber-juno 0.3.0 
```

### Additional Information

**Comment by savetheclocktower** [comment]
That's not a fun one. Open the the `incompatible-packages.js` file for editing and replace each instance of the word `package` with anything else, like `pkg`.

**Comment by goyalyashpal** [comment]
<img src="https://user-images.githubusercontent.com/19423063/231703776-a9455bab-2f03-49f9-bc63-88b901371a2e.png" width=400px/>

----

### Versions

**Atom**: 1.103.0 x64
**Electron**: 12.2.3
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: [ink](https://github.com/JunoLab/atom-ink) package 0.12.6


### Stack Trace

Failed to activate the ink package

```
At subs is not defined

ReferenceError: subs is not defined
    at Function.activate (pane.js:14:9)
    at Object.activate (linter.js:13:14)
    at Object.activate (/packages/ink/lib/ink.coffee:48:9)
    at Package.activateNow (/app.asar/src/package.js:242:27)
    at /app.asar/src/package.js:211:27
    at Package.measure (/app.asar/src/package.js:82:19)
    at /app.asar/src/package.js:205:14
    at new Promise (<anonymous>)
    at Package.activate (/app.asar/src/package.js:203:32)
    at PackageManager.activatePackage (/app.asar/src/package-manager.js:780:36)
    at /app.asar/node_modules/settings-view/lib/package-manager.coffee:321:25
    at exit (/app.asar/node_modules/settings-view/lib/package-manager.coffee:68:7)
    at triggerExitCallback (/app.asar/src/buffered-process.js:280:9)
    at /app.asar/src/buffered-process.js:310:9)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
```

### Non-Core Packages

```
hyperclick 0.1.5 
indent-detective 0.4.0 
ink 0.12.6 
language-julia 0.22.1 
latex-completions 0.3.6 
tool-bar 1.4.4 
uber-juno 0.3.0 
```

**Comment by savetheclocktower** [comment]
Man, that's a bit sloppy on the package author's part — using a variable without declaring it first.

https://github.com/JunoLab/atom-ink/blob/master/lib/linter/pane.js#L14

You can change both instances of `subs` to `this.subs` in this file and that'll fix that specific error.

**Comment by savetheclocktower** [comment]
Maybe `atom-ink` should be added to our informal list of packages needing adoption.

**Comment by confused-Techie** [comment]
@savetheclocktower It may also be beneficial to add a badge to this package, since it does not work at all without manual edits.

**Comment by confused-Techie** [comment]
@goyalyashpal So I've talked further with the team about this issue. 

Essentially the conclusion we've come to, is that while I understand it might be frustrating for things to not work properly, like I mentioned the only resource I can find about users changing the `ComSpec` value to something else is the chance of things breaking is likely.

And there's no realistic way to support this. If we go out of the way to support this particular program, that would also mean we need to support users changing this value to cygwin, gitbash, or a dozen other possible applications that might be used. And tbh, Pulsar itself never calls on `ComSpec` the NodeJS module `fs` does, which is the standard in operating on the filesystem, and to hack around it likely won't be an easy task at all. 

So all in all, I'm glad we were able to pursue some other issues with specific packages, but as for the reason you made this issue I don't believe we will be able to support it. Thanks a ton for reporting this issue though and contributing!

**Comment by goyalyashpal** [comment]
btw, i just noticed that i never mentioned what the expected outcome is / solution can be...

supporting non-cmd is not an option as u noted, but maybe on the event of occuring a failure, comspec can be checked and if found guilty, then a more helpful error might be raised; smth like "ComSpec found to be xyz, try resetting it back to cmd"

but yeah, to be honest, thus is too corner of a use-case (& that too which's broken anyway - see comment below) - so even this may not be worth doing it...

**Comment by goyalyashpal** [comment]
yeah, lots of things break on changing comspec i.e. are dependent on it being cmd... 
* opening of bat files from explorers (on double clicking, via start menu etc) (https://github.com/msys2/MSYS2-packages/issues/3102)
* iirc, this (.bat) one also affects proper use of python virtual environments as those supply only a bat file for the venv activation
* detection of python by `ms-python` extension for vscodium (https://github.com/VSCodium/vscodium/discussions/1278#discussioncomment-5504011)
* there were probably several others but i dont remember...
