### ISSUE TITLE
Error: Path must be a valid path to a file or directory

### ISSUE THREAD

**Issue by asiloisad** [pulsar-edit/pulsar#520]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

Hello, the bug has occure every time I'm opening project localized at NAS. I have checked and problem occure whatever path is symlink or not. A bug has occur, but I don't know what feature is breaked, because everythink looks good.

### Pulsar version

1.104.2023041706

### Which OS does this happen on?

🪟 Windows

### OS details

10 22H2

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

,,Open folder'' at NAS directory

![image](https://user-images.githubusercontent.com/29706474/236795363-8ef3a983-02c6-416b-8e1d-9d96f3c014a4.png)

,,Add project folder' at NAS directory

![image](https://user-images.githubusercontent.com/29706474/236795401-19e0f511-a3b9-4e3e-bdb8-80546ec0b5dd.png)

**Comment by confused-Techie** [comment]
Thanks a ton for the issue report.

 I just want to confirm though when you say NAS directory you mean a directory within a Network Attached Storage.

Since you are on Windows, I also want to make sure of how you are accessing this directory so we can properly test.

Is this NAS mounted as a drive to your system? Or are you accessing it via a UNC path? How is this NAS setup? Is it an NFS share? Or something else?

But thanks a ton for reporting this! I can see based on the log, that the error is originating in NSFW, which is the file and directory watcher within Pulsar, so seems it's having trouble reading data across the network

**Comment by asiloisad** [comment]
hi, you are right, I mean NAS == Network Attached Storage 👍 

direct path:
![image](https://user-images.githubusercontent.com/29706474/236981218-70759108-c43b-4a43-8cbd-26448c9431f1.png)

symlink path:
![image](https://user-images.githubusercontent.com/29706474/236981359-7da65271-56ff-4527-af46-75aa96a6c1b0.png)

mapped drive:
![image](https://user-images.githubusercontent.com/29706474/236981516-312ea41d-4b28-4592-b103-73449ef788f5.png)

as you see, the uncaught error has occur in every case.

My NAS is NEGEAR ReadyNAS 426, I'm using SMB service, the tested localization has permissions to read/write for everyone (no account needed). If you need some more information about configuration tell me what's needed 👍

**Comment by confused-Techie** [comment]
@asiloisad This is beautiful!
Can't thank you enough for such detailed information!

I have a NAS with a similar setup myself, and access to Windows machine to try and test a bit, I'll see what I can do here, appreciate you!

**Comment by confused-Techie** [comment]
So I just wanted to add some troubleshooting here, even if it doesn't quite show where the error is happening.

So NSFW uses `fs-extra` to interact with the file system here, so I tried the following tests to see if both FS and FSE where able to properly recognize and read a directory and file at their provided path using State. Sure this doesn't cover all cases of what's happening here, but can hopefully provide a jumping off point:

- ✅FS: UNC Path (Proper Escapes) - "\\\\my-server\\mypath"
- ✅FSE: UNC Path (Proper Escapes) - "\\\\my-server\\mypath"
- ❌FS: UNC Path (Bad Escapes) - "\\my-server\mypath"
- ❌FSE: UNC Path (Bad Escapes) - "\\my-server\mypath"
- ❌FS: IP UNC Style (Bad Escapes)" - "\\10.10.10.3\Utils"
- ❌FSE: IP UNC Style (Bad Escapes)" - "\\10.10.10.3\Utils"
- ✅FS: IP UNC Style (Proper Escapes) - "\\\\10.10.10.3\\Utils"
- ✅FSE: IP UNC Style (Proper Escapes) - "\\\\10.10.10.3\\Utils"
- ✅FS: Network Mapped Drive - "Q:\\Videos"
- ✅FSE: Network Mapped Drive - "Q:\\Videos"


Even more, since the network mapping failed for the OP above, I tested within Pulsar and wasn't able to receive any errors based on my network mapped location.

**Comment by savetheclocktower** [comment]
@asiloisad, have you noticed whether this is a problem with the `@parcel/watcher` implementation?

This ticket should stay open until we solve this once and for all, but I'm curious whether swapping out `nsfw` would put us on the right track.

**Comment by asiloisad** [comment]
I'm no longer use NAS, but  I can reproduce it on stable branch by opening project in workgroup directory e.g. `\\192.168.0.99\Shared`. 

A build from branch @parcel/watcher push some logs and errors to dev console too.

```
[PathWatcher] new WatcherTask: C:\Program Files\Pulsar\resources\app.asar\src\nsfw-watcher-worker.js
C:\Program Files\Pulsar\resources\app.asar\src\watcher-task.js:58 

[PathWatcher] Start called for worker with task path: C:\Program Files\Pulsar\resources\app.asar\src\nsfw-watcher-worker.js
C:\Program Files\Pulsar\resources\app.asar\src\watcher-task.js:25 

Creating child process at task path: C:\Program Files\Pulsar\resources\app.asar\src\nsfw-watcher-worker.js
C:\Program Files\Pulsar\resources\app.asar\src\watcher-task.js:73 

Sending: Object to process with task path: C:\Program Files\Pulsar\resources\app.asar\src\nsfw-watcher-worker.js
C:\Program Files\Pulsar\resources\app.asar\src\watcher-task.js:73 

Sending: {"id":"2cdd7127c2","event":"watcher:watch","args":{"normalizedPath":"C:\\Users\\asiloisad\\.pulsar\\styles.less","instance":"8feead5b9f"}} to process with task path: C:\Program Files\Pulsar\resources\app.asar\src\nsfw-watcher-worker.js
C:\Program Files\Pulsar\resources\app.asar\src\watcher-task.js:73 

Sending: {"id":"54fa08145a","event":"watcher:watch","args":{"normalizedPath":"\\192.168.0.99\\Shared\\[20260223] [PXXXX] Most w Krosnowicach","instance":"ceb4c210d9"}} to process with task path: C:\Program Files\Pulsar\resources\app.asar\src\nsfw-watcher-worker.js
C:\Program Files\Pulsar\resources\app.asar\src\path-watcher.js:246 

nsfw-worker Error trying to watch path: \192.168.0.99\Shared\[20260223] [PXXXX] Most w Krosnowicach Path must be a valid path to a file or a directory.
(anonymous) @ C:\Program Files\Pulsar\resources\app.asar\src\path-watcher.js:246

C:\Program Files\Pulsar\resources\app.asar\src\path-watcher.js:219 
Uncaught (in promise) Error: Path must be a valid path to a file or a directory.
    at C:\Program Files\Pulsar\resources\app.asar\src\path-watcher.js:219:17
    at C:\Program Files\Pulsar\resources\app.asar\src\watcher-task.js:84:7
    at Function.simpleDispatch (C:\Program Files\Pulsar\resources\app.asar\node_modules\event-kit\dist\emitter.js:64:14)
    at Emitter.emit (C:\Program Files\Pulsar\resources\app.asar\node_modules\event-kit\dist\emitter.js:257:28)
    at ChildProcess.<anonymous> (C:\Program Files\Pulsar\resources\app.asar\src\watcher-task.js:40:20)
    at ChildProcess.emit (node:events:518:28)
    at emit (node:internal/child_process:951:14)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

On the other hand, the watcher looks like it's working fine. I'm changing the content of files and the files themselves on the second PC, and the changes are reflected in Pulsar on my PC.

**Comment by savetheclocktower** [comment]
Fair enough. Thanks for checking! It was a long shot.

I don't know that there's a good workaround for this, but I'm pretty sure this gracefully degrades, aside from the error in the console. If you're editing a file on a NAS or an SMB share, it doesn't surprise me that file-watching (via FSEvent and the like) doesn't work.

From what I can tell, VS Code's way around this is simply to fall back to manual polling whenever the more efficient methods fail to work. That's something we don't even attempt to do. But we probably should, eventually!
