### ISSUE TITLE
`jupyter-notebook` "Compiler tools not found"

### ISSUE THREAD

**Issue by goyalyashpal** [pulsar-edit/pulsar#586]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [ ] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [ ] Have you checked you are on the latest release of Pulsar?

* Duplicates checked: 🔍 : [compiler tools], [jupyter]

[compiler tools]: https://github.com/pulsar-edit/pulsar/issues?q=compiler+tools
[jupyter]: https://github.com/pulsar-edit/pulsar/issues?q=jupyter

### What happened?

```
Installing “jupyter-notebook@0.0.10” failed.Show output…
⚠ Compiler tools not found
Packages that depend on modules that contain C/C++ code will fail to install.
Please install Python and Visual Studio to continue.
Run pulsar -p install --check after installing to test compiling a native module.
```

<details>
<summary>Show output</summary>

```

> bufferutil@1.2.1 install C:\Users\USR~1\AppData\Local\Temp\apm-install-dir-2023512-7668-1vbpn4t.ekys\node_modules\jupyter-notebook\node_modules\bufferutil
> node-gyp rebuild


C:\Users\USR~1\AppData\Local\Temp\apm-install-dir-2023512-7668-1vbpn4t.ekys\node_modules\jupyter-notebook\node_modules\bufferutil>if not defined npm_config_node_gyp (node "D:\ProgramFiles\Pulsar\resources\app\ppm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "D:\ProgramFiles\Pulsar\resources\app\ppm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 

> utf-8-validate@1.2.2 install C:\Users\USR~1\AppData\Local\Temp\apm-install-dir-2023512-7668-1vbpn4t.ekys\node_modules\jupyter-notebook\node_modules\utf-8-validate
> node-gyp rebuild


C:\Users\USR~1\AppData\Local\Temp\apm-install-dir-2023512-7668-1vbpn4t.ekys\node_modules\jupyter-notebook\node_modules\utf-8-validate>if not defined npm_config_node_gyp (node "D:\ProgramFiles\Pulsar\resources\app\ppm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "D:\ProgramFiles\Pulsar\resources\app\ppm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 

> pathwatcher@8.1.2 install C:\Users\USR~1\AppData\Local\Temp\apm-install-dir-2023512-7668-1vbpn4t.ekys\node_modules\jupyter-notebook\node_modules\pathwatcher
> node-gyp rebuild


C:\Users\USR~1\AppData\Local\Temp\apm-install-dir-2023512-7668-1vbpn4t.ekys\node_modules\jupyter-notebook\node_modules\pathwatcher>if not defined npm_config_node_gyp (node "D:\ProgramFiles\Pulsar\resources\app\ppm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "D:\ProgramFiles\Pulsar\resources\app\ppm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 

npm WARN deprecated uuid@2.0.3: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated jupyter-js-services@0.21.1: This package has moved to @jupyterlab/services
npm WARN deprecated core-js@1.2.7: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
npm WARN deprecated phosphor@0.5.0: use @phosphor/ packages
gyp ERR! find VS 
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS 
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS 
gyp ERR! configure error 
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (D:\ProgramFiles\Pulsar\resources\app\ppm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at D:\ProgramFiles\Pulsar\resources\app\ppm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (D:\ProgramFiles\Pulsar\resources\app\ppm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at D:\ProgramFiles\Pulsar\resources\app\ppm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
gyp ERR! stack     at D:\ProgramFiles\Pulsar\resources\app\ppm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at D:\ProgramFiles\Pulsar\resources\app\ppm\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at D:\ProgramFiles\Pulsar\resources\app\ppm\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (node:child_process:333:5)
gyp ERR! stack     at ChildProcess.emit (node:events:365:28)
gyp ERR! stack     at maybeClose (node:internal/child_process:1067:16)
gyp ERR! System Windows_NT 10.0.19045
gyp ERR! command "D:\\ProgramFiles\\Pulsar\\resources\\app\\ppm\\bin\\node.exe" "D:\\ProgramFiles\\Pulsar\\resources\\app\\ppm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\USR~1\AppData\Local\Temp\apm-install-dir-2023512-7668-1vbpn4t.ekys\node_modules\jupyter-notebook\node_modules\bufferutil
gyp ERR! node -v v16.0.0
gyp ERR! node-gyp -v v5.1.1
gyp ERR! not ok 
gyp ERR! find VS 
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS 
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS 
gyp ERR! configure error 
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (D:\ProgramFiles\Pulsar\resources\app\ppm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at D:\ProgramFiles\Pulsar\resources\app\ppm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (D:\ProgramFiles\Pulsar\resources\app\ppm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at D:\ProgramFiles\Pulsar\resources\app\ppm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
gyp ERR! stack     at D:\ProgramFiles\Pulsar\resources\app\ppm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at D:\ProgramFiles\Pulsar\resources\app\ppm\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at D:\ProgramFiles\Pulsar\resources\app\ppm\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (node:child_process:333:5)
gyp ERR! stack     at ChildProcess.emit (node:events:365:28)
gyp ERR! stack     at maybeClose (node:internal/child_process:1067:16)
gyp ERR! System Windows_NT 10.0.19045
gyp ERR! command "D:\\ProgramFiles\\Pulsar\\resources\\app\\ppm\\bin\\node.exe" "D:\\ProgramFiles\\Pulsar\\resources\\app\\ppm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\USR~1\AppData\Local\Temp\apm-install-dir-2023512-7668-1vbpn4t.ekys\node_modules\jupyter-notebook\node_modules\utf-8-validate
gyp ERR! node -v v16.0.0
gyp ERR! node-gyp -v v5.1.1
gyp ERR! not ok 
gyp ERR! find VS 
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS 
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS 
gyp ERR! configure error 
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (D:\ProgramFiles\Pulsar\resources\app\ppm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at D:\ProgramFiles\Pulsar\resources\app\ppm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (D:\ProgramFiles\Pulsar\resources\app\ppm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at D:\ProgramFiles\Pulsar\resources\app\ppm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
gyp ERR! stack     at D:\ProgramFiles\Pulsar\resources\app\ppm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at D:\ProgramFiles\Pulsar\resources\app\ppm\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at D:\ProgramFiles\Pulsar\resources\app\ppm\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (node:child_process:333:5)
gyp ERR! stack     at ChildProcess.emit (node:events:365:28)
gyp ERR! stack     at maybeClose (node:internal/child_process:1067:16)
gyp ERR! System Windows_NT 10.0.19045
gyp ERR! command "D:\\ProgramFiles\\Pulsar\\resources\\app\\ppm\\bin\\node.exe" "D:\\ProgramFiles\\Pulsar\\resources\\app\\ppm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\USR~1\AppData\Local\Temp\apm-install-dir-2023512-7668-1vbpn4t.ekys\node_modules\jupyter-notebook\node_modules\pathwatcher
gyp ERR! node -v v16.0.0
gyp ERR! node-gyp -v v5.1.1
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\USR~1\AppData\Local\Temp\apm-install-dir-2023512-7668-1vbpn4t.ekys\package.json'
npm WARN apm-install-dir-2023512-7668-1vbpn4t.ekys No description
npm WARN apm-install-dir-2023512-7668-1vbpn4t.ekys No repository field.
npm WARN apm-install-dir-2023512-7668-1vbpn4t.ekys No README data
npm WARN apm-install-dir-2023512-7668-1vbpn4t.ekys No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@1.2.1 (node_modules\jupyter-notebook\node_modules\bufferutil):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@1.2.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: utf-8-validate@1.2.2 (node_modules\jupyter-notebook\node_modules\utf-8-validate):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: utf-8-validate@1.2.2 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pathwatcher@8.1.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pathwatcher@8.1.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\NemoUSR\.pulsar\.apm\_logs\2023-06-12T00_56_04_428Z-debug.log
```

</details> 

### Pulsar version

1.103.0

### Which OS does this happen on?

🪟 Windows

### OS details

Win 10 22H2

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

1. Open Pulsar
2. Go to Package Manager < Package or Settings (`^,`) < File
3. Go to Install tab in the sidebar
4. Install `jupyter-notebook`

**Comment by confused-Techie** [comment]
So like the error message says above. Some community package's contain native modules that need to be compiled for your operating system.

This means in order to compile them you'll have to install a C++ toolchain. Like the error says on Windows you'll need Visual Studio and Python installed.

It's recommended to install:

* Visual Studio 2019
* Python 3.10

**Comment by goyalyashpal** [comment]
umh, this feels counterintuitive - like 😅 i am trying to install packages, not build them from source

besides, i do have python installed, 



(technically, also the C++ toolchain of MSYS2 - already used by lots of projects - but not & never the MSVS one)

**Comment by confused-Techie** [comment]
I see what you mean, but we can't control the source code of community packages. Similar to the NPM world, many community packages don't ship with the binaries needed, and leave it up to whatever client installs them to then build that native modules needed for the package to run.

And that's good that you have Python installed, but you'll also need Visual Studio 2019. PPM uses `node-gyp` to build it's native modules (as does NPM) so MSYS2 isn't supported as far as I know unfortunately

**Comment by goyalyashpal** [comment]
this "node" thing is chasing me like crazy lol... the pulsar, & md rendering
seems i will have to learn that too 😆👀

**Comment by confused-Techie** [comment]
I wouldn't say you have to learn NodeJS to use Pulsar. The reason it seems to be 'chasing' you, is that Pulsar runs on Electron, which itself is using NodeJS. 

So really beyond having Pulsar, Visual Studio, and Python installed, there shouldn't be to much more to learn about them unless you are developing Pulsar or attempting to use some advanced feature sets.

**Comment by goyalyashpal** [comment]
so, i asked ChatGPT (model: **gpt-3.5-turbo**) about this; and it said following.
obviously, i know that it's reliability can only be known _after_ actually trying this... but didn't have time atm; 
will try someday later.
meanwhile, for anyone curious, here's the chatlog:

----

<details>
<summary>

> how to make node-gyp to use msys2 toolchain for building C++ native modules instead of microsoft Visual Studio
</summary>

To make node-gyp use the msys2 toolchain for building C++ native modules instead of Microsoft Visual Studio, you can follow these steps:

1\. Install msys2 by following the instructions on their website: https://www.msys2.org/
2. Open the msys2 terminal and install the necessary packages by running the following command:

   
   `pacman -S mingw-w64-x86_64-toolchain`
   

   This will install the toolchain needed for building C++ modules.

3. Set the environment variable `GYP_MSVS_VERSION` to an empty string to disable the use of Microsoft Visual Studio:

   
   `set GYP_MSVS_VERSION=`
   

4. Set the environment variable `npm_config_node_gyp` to use the msys2 toolchain:

   
   `set npm_config_node_gyp="C:\msys64\mingw64\bin\node-gyp.cmd"`
   

   Replace `C:\msys64` with the path where you installed msys2.

5. Run `npm install` to build your C++ native module using the msys2 toolchain.

Note that this approach may not work for all C++ native modules, as some may have specific dependencies or requirements that are only met by Microsoft Visual Studio. In such cases, you may need to use Microsoft Visual Studio or another compatible toolchain.

</details>

**Comment by goyalyashpal** [comment]
_self hiding as outdated_

----
ohw it was zucking issue ..... 

*hit MacroHard corporate making dev's life miserable 
in all corners of per's endeavors 
be python, be JS/npm, be dont know how many more
via this *hit μs oh sorry, 
MH Stisual Vudio torchure for C/C++. 
Google, please bring ur Carbon to end this C/C++ monopoly 
as u did with chrome for exploror


* https://github.com/davisking/dlib/issues/2652#issuecomment-1645640974
