### ISSUE TITLE
Styleguide + reload: Uncaught TypeError: this.grammar.onDidUpdate is not a function

### ISSUE THREAD

**Issue by asiloisad** [pulsar-edit/pulsar#626]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

An uncaught error has occur if window is realoded while styleguide is open.

```
At C:\Users\asiloisad\AppData\Local\Programs\Pulsar\resources\app.asar\src\text-mate-language-mode.js:43

TypeError: this.grammar.onDidUpdate is not a function
    at /app.asar/src/text-mate-language-mode.js:43:20)
    at GrammarRegistry.languageModeForGrammarAndBuffer (/app.asar/src/grammar-registry.js:220:14)
    at GrammarRegistry.assignLanguageMode (/app.asar/src/grammar-registry.js:150:14)
    at /app.asar/node_modules/styleguide/lib/code-block.js:9:19)
    at render (/app.asar/node_modules/bookmarks/node_modules/etch/lib/render.js:17:25)
    at addChildren (/app.asar/node_modules/bookmarks/node_modules/etch/lib/render.js:39:24)
    at render (/app.asar/node_modules/bookmarks/node_modules/etch/lib/render.js:29:21)
    at addChildren (/app.asar/node_modules/bookmarks/node_modules/etch/lib/render.js:39:24)
    at render (/app.asar/node_modules/bookmarks/node_modules/etch/lib/render.js:29:21)
    at updateChildren (/app.asar/node_modules/deprecation-cop/node_modules/etch/lib/patch.js:109:34)
    at patch (/app.asar/node_modules/deprecation-cop/node_modules/etch/lib/patch.js:15:9)
    at updateSync (/app.asar/node_modules/deprecation-cop/node_modules/etch/lib/component-helpers.js:108:20)
    at /app.asar/node_modules/deprecation-cop/node_modules/etch/lib/component-helpers.js:72:7
    at DefaultScheduler.performUpdates (/app.asar/node_modules/etch/lib/default-scheduler.js:48:34)
```

### Pulsar version

1.106.0

### Which OS does this happen on?

🪟 Windows

### OS details

10 22H2

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

1. open Pulsar
2. open Styleguide `styleguide:show`
3. Reload window `window:reload`

**Comment by confused-Techie** [comment]
Thanks a ton for reporting this, but looks like a duplicate of #560

**Comment by asiloisad** [comment]
You are right, the error is similar (or the same), but #560 occur only in dev-console. This one has error notification. I think the difference is #560 was reported in 1.105.2023052201 and this one in 1.106.0

**Comment by asiloisad** [comment]
https://github.com/pulsar-edit/pulsar/pull/648
