### ISSUE TITLE
[autocomplete-html] Throwing Error when autocompleting EJS

### ISSUE THREAD

**Issue by confused-Techie** [pulsar-edit/pulsar#649]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

If writing an EJS file, when attempting to write any of the characters following `viewport" ` this error is thrown.

The reproducible code is below:

```ejs
<!DOCTYPE HTML>
<html lang="en">
  <head>
    <title><%=title%></title>
    <meta name="viewport" content
```

The stack trace is below:

```
Uncaught TypeError: Cannot read property 'child' of null

At C:\Users\USER_NAME_REDACTED\AppData\Local\Programs\pulsar\resources\app.asar\node_modules\autocomplete-html\lib\tree-sitter-provider.js:32

TypeError: Cannot read property 'child' of null
    at module.exports (/app.asar/node_modules/autocomplete-html/lib/tree-sitter-provider.js:32:35)
    at Object.getSuggestions (/app.asar/node_modules/autocomplete-html/lib/main.js:12:14)
    at /app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:287:52
    at Array.forEach (<anonymous>)
    at AutocompleteManager.getSuggestionsFromProviders (/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:258:15)
    at AutocompleteManager.findSuggestions (/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:250:17)
    at AutocompleteManager.requestNewSuggestions (/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:697:12)
    at AutocompleteManager.showOrHideSuggestionListForBufferChanges (/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:763:12)
    at Function.simpleDispatch (/app.asar/node_modules/event-kit/dist/emitter.js:64:14)
    at Emitter.emit (/app.asar/node_modules/event-kit/dist/emitter.js:257:28)
    at TextBuffer.emitDidChangeTextEvent (/app.asar/node_modules/text-buffer/lib/text-buffer.js:2374:24)
    at TextBuffer.transact (/app.asar/node_modules/text-buffer/lib/text-buffer.js:1337:10)
    at TextEditor.transact (/app.asar/src/text-editor.js:2467:24)
    at /app.asar/src/text-editor.js:1799:19
    at TextEditor.mergeSelections (/app.asar/src/text-editor.js:4050:47)
    at TextEditor.mergeIntersectingSelections (/app.asar/src/text-editor.js:4015:10)
    at TextEditor.mutateSelectedText (/app.asar/src/text-editor.js:1798:17)
    at TextEditor.insertText (/app.asar/src/text-editor.js:1747:25)
    at /app.asar/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
    at TextEditorComponent.didTextInput (/app.asar/src/text-editor-component.js:1838:24)
```

Additional details:

```
**Pulsar**: 1.107.0 x64
**Electron**: 12.2.3
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [autocomplete-html](https://github.com/pulsar-edit/pulsar) package 0.8.9
```

### Pulsar version

1.107.0

### Which OS does this happen on?

🪟 Windows

### OS details

10 22H2

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

1. Create `any.ejs`
2. Copy and Paste in the example code provided
3. Remove `content` from the last line
4. Type in `content` slowly, and see error thrown

### Additional Information:

Hate to say, this may look like more of the same `autocomplete-css` shenanigans

**Comment by savetheclocktower** [comment]
Yeah, this one also has to do with strange behavior from error handling. You can go to the [Tree-sitter playground](https://tree-sitter.github.io/tree-sitter/playground) and paste that HTML to demonstrate the problem — the tree is much flatter than it seems like it should be: 

<img width="484" alt="Screenshot 2023-07-18 at 11 36 54 PM" src="https://github.com/pulsar-edit/pulsar/assets/3450/8819d4b0-fccf-4467-85b1-934625481c0f">

And because it assumes that every `attribute_node` will have a grandparent, it tries to read from `null`. In this case, `attribute_name` isn't even a child of `attribute`.

If you were to add the closing `</head>` and `</html>`, you'd see a much more accurate tree. Hell, if you even just insert a line break afterward, the tree is still broken — but just orderly enough for the completion to work.

The immediate fix is to do a `try`/`catch`, or to do some sort of traversal that bails if it encounters an `ERROR` node, or something like that. In those cases we can just give up on trying to autocomplete.

A longer-term fix might involve using a tree cursor to walk backward until we find a `tag_name` node, even if it doesn't have the exact hierarchical relationship that we're expecting.
