### ISSUE TITLE
text-editor-component.js Error: Cannot read property 'element' of undefined 

### ISSUE THREAD

**Issue by FibroJedi** [pulsar-edit/pulsar#920]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

Firstly, I cannot reproduce the error because I don't know how it happened. I just re-focused Pulsar after working in a different program (a browser). But I had to tick the above box, but no I didn't do it in safe mode. Hope that's okay for once?

I got the shiny red box that said "This is likely a bug in Pulsar. You can help by creating an issue".

So I have. But, aside from focusing a Pulsar window with about 10 open documents in it, I didn't do anything else.

`Uncaught TypeError: Cannot read property 'element' of undefined

/opt/Pulsar/resources/app.asar/src/text-editor-component.js:1776
[Hide Stack Trace](https://github.com/pulsar-edit/pulsar/issues/new?assignees=&labels=bug%2Ctriage&projects=&template=bug-report.yml#)
TypeError: Cannot read property 'element' of undefined
    at TextEditorComponent.didScrollDummyScrollbar (/opt/Pulsar/resources/app.asar/src/text-editor-component.js:1776:37)`

### Pulsar version

1.113.0 (x64)

### Which OS does this happen on?

🐧 Debian based (Linux Mint, Ubuntu, etc.)

### OS details

Linux Mint 21 (Cinnamon 5.4.12, Linux Kernel: 6.5.0-17-generic)

### Which CPU architecture are you running this on?

x86_64/AMD64

### What steps are needed to reproduce this?

1. Spend time in a different window
2. Alt-tab to Pulsar window
(that's all I did and I can't reproduce it, as mentioned above)

**Comment by confused-Techie** [comment]
Thanks a ton for reporting this issue! We will have to take a look at it

**Comment by asiloisad** [comment]
Can you insert a list of community packages have you installed?

**Comment by FibroJedi** [comment]
Sure, but it's pretty long!

atom-complete-php
atom-beautify
atom-minify
atom-php-lookup
atom-tag-wrapper
atom-wordpress
autoclose-tags
autocomplete-wordpress-hooks
autosave-onchange
busy-signal
click-bookmarks
csslint
goto-definition
highlight-bad-chars
highlight-colors
intentions
keybinding-cheatsheet
language-htaccess
language-ini
linter
linter-eslint
linter-php
linter-ui-default
php-hover-documentation
php-tools
project-manager
project-manager-ide
smart-html-tags
tool-bar
tool-bar-main
uglify-html
wordpress-api
wordpress-autocomplete
wordpress-dictionary

**Comment by WalnussPower** [comment]
I had something similar happen to me.



### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Pulsar package that provides the described functionality: <https://atom.io/packages>

### Description

The error just occured when starting Pulsar.

### Steps to Reproduce

1. Close Pulsar with project and files open
2. Reboot machine
3. Start Pulsar

**Expected behavior:**

no errors

**Actual behavior:**

this error

### Versions

**Pulsar**: 1.118.0 x64
**Electron**: 12.2.3
**OS**: Pop!_OS 22.04
**Thrown From**: Pulsar Core


### Stack Trace

Uncaught TypeError: Cannot read property 'element' of undefined

```
At /opt/Pulsar/resources/app.asar/src/text-editor-component.js:1776

TypeError: Cannot read property 'element' of undefined
    at TextEditorComponent.didScrollDummyScrollbar (/app.asar/src/text-editor-component.js:1776:37)
```

### Commands

```
```

### Non-Core Packages

```
atom-clock 0.1.18 
atom-django 0.3.2 
atom-easy-jsdoc 4.12.5 
atom-file-icons 0.7.1 
atom-ide-base 3.4.0 
atom-ide-code-format 1.0.3 
atom-ide-datatip 0.25.0 
atom-ide-debugger-python 0.7.3 
atom-ide-definitions 0.4.2 
atom-ide-hyperclick 1.0.11 
atom-ide-markdown-service 2.1.0 
atom-ide-outline 3.2.0 
atom-ide-signature-help 0.16.0 
atom-ide-ui 0.13.0 
atom-material-syntax 1.0.8 
atom-material-syntax-light 0.4.6 
atom-material-ui 2.1.3 
atom-mermaid 3.7.1 
atom-solarized-dark-ui 0.28.1 
atom-typescript 14.4.0 
atom-visual-studio-code-light-ui 2.1.0 
autocomplete-lua 0.9.2 
autocomplete-paths 2.17.0 
base16-syntax 1.8.1 
busy-signal 2.0.1 
city-lights-syntax 1.1.8 
city-lights-ui 1.5.3 
clear-night-syntax 1.3.18 
django-templates 0.5.0 
dracula-night-syntax 0.5.0 
dracula-syntax 3.0.2 
editorconfig 2.6.1 
file-icons 2.1.47 
font-preview 0.1.2 
front-icons 1.18.0 
git-blame 1.8.0 
gl-light-syntax 3.0.0 
hip-light-ui-theme 1.1.1 
ide-csharp 0.6.2 
ide-css 0.4.0 
ide-typescript 0.9.5 
ide-yaml 0.8.0 
intentions 2.1.1 
javascript-drag-import 0.1.13 
language-hjson 1.0.2 
language-ini-desktop 1.18.3 
language-latex 1.2.0 
language-log 1.10.1 
language-lua 0.9.11 
language-mermaid 0.6.0 
language-svg 0.9.2 
latex-tree 0.5.0 
linter 3.4.0 
linter-eslint 9.0.1 
linter-luaparse 0.2.0 
linter-spell 0.15.0 
linter-ui-default 3.4.1 
markdown-code-blocks 1.3.0 
one-light-material-syntax 1.10.0 
pdfjs-viewer 1.3.0 
pop-contrast-syntax 0.4.1 
pop-syntax 0.5.0 
pop-ui 0.6.1 
pp-markdown 0.0.2 
project-manager 3.3.8 
pulsar-ide-python 1.11.1 
spell-check-urls 0.5.1 
summer-night-syntax 2.0.1 
svg-icons 0.8.1 
svg-preview 0.14.0 
svgo 5.0.0 
tomorrow-night-eighties-syntax 1.1.0 
too-much-sunlight-syntax 0.1.0 
unleash-django 1.3.2 
wasco-syntax 1.2.0 
```

### Additional Information
