### ISSUE TITLE
failed to map segment from shared object

### ISSUE THREAD

**Issue by Ofloo** [pulsar-edit/pulsar#999]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

```
/Pulsar-1.116.2024050605.AppImage --no-sandbox
/tmp/.org.chromium.Chromium.whTx1z: failed to map segment from shared object
Error: /tmp/.org.chromium.Chromium.whTx1z: failed to map segment from shared object
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2073)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/tmp/.mount_PulsarQ1H9YF/resources/app.asar/node_modules/nsfw/js/src/index.js:4:14)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
```
```
/opt/Pulsar/pulsar 
/tmp/.org.chromium.Chromium.PlS5ih: failed to map segment from shared object
Error: /tmp/.org.chromium.Chromium.PlS5ih: failed to map segment from shared object
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2073)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/opt/Pulsar/resources/app.asar/node_modules/nsfw/js/src/index.js:4:14)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
```

### Pulsar version

1.116.2024050605 & 1.116.0

### Which OS does this happen on?

🐧 Debian based (Linux Mint, Ubuntu, etc.)

### OS details

Ubuntu 23.10 mantic

### Which CPU architecture are you running this on?

x86_64/AMD64

### What steps are needed to reproduce this?

Just run from console appimage or binary

**Comment by confused-Techie** [comment]
I've transferred this issue to the Pulsar repo, as the `pulsar-rolling-releases` repo only deals with hosting of various versions of the Pulsar binary, not with any of the actual building of Pulsar itself.

**Comment by ChrisLeinbach** [comment]
I've also encountered this issue. Occurred with the RPM versions of both Pulsar 1.116.0 and 1.117.0.

Running AlmaLinux 9.4 on an Intel x86_64 system.

**Comment by Ofloo** [comment]
mount -o remount,exec /tmp

**Comment by ChrisLeinbach** [comment]
Remounting /tmp with exec is probably not a good long term solution. noexec on /tmp and /var/tmp is common for hardened systems. 

It looks like a lot of JS based projects have run into this issue and it stems from Chromium (See [Signal-Desktop #2707](https://github.com/signalapp/Signal-Desktop/issues/2707) for example).

It looks like overriding the tmpdir environment variable just for Pulsar is the safer solution. I'm going to implement that via a script that wraps the Pulsar binary on my system but it may be worthwhile considering implementing such a fix by default.

**Comment by Ofloo** [comment]
Well I'm not saying that it should be a long term solution. Just saying that this allows you to start the program.

**Comment by Ofloo** [comment]
Not sure how you would go about doing that, but sounds like you would like to remount to exec start program then remount to noexec, .. that would mean you'd need to start a script with sudo each time? Not saying that this can't work, only wondering if it's such a good idea to do this?

**Comment by ChrisLeinbach** [comment]
I was actually able to find where Pulsar sets the location of the tmp files. (See pulsar.sh line 131)

I'll submit a pull request to move that to something like /opt/Pulsar/tmp shortly.

For posterity sake, what I mean't before was that Chromium should obey the TMPDIR variable if it is set and if not it should fall back to /tmp. The script I was talking about could simply set TMPDIR to somewhere with exec and then call Pulsar. This shouldn't be needed if the place where I can see TMPDIR being referenced in pulsar.sh works out the way I believe it should.
